# This is an example of overriding the application.yml file with the OS environment variables.

# Basic configuration for the application
app-object:
  name: "Spring Boot Overriding Environment Variables"
  version: "0.0.1"
  description: "Spring Boot Overriding Environment Variables with application.yml"
  author: "Cevheri"
  email: "cevheribozoglan@gmail.com"

# Advanced configuration Array values
app-arrays:
  roles:
    - array-create
    - array-read
    - array-update
    - array-delete
    - array-admin

# Advanced configuration Array in Array values
app-multiple:
  paths:
    - method: POST
      roles:
        - path-create
        - path-read
        - path-update
        - path-delete
        - path-admin
